jobs:

  borrow_problematic_scenarios:

    name: 'Borrow: Problematic Scenarios'

    description: |
      Run Borrow problematic scenarios under MRI

    priority: -1

    run_when:
      branch name matches master or borrow:
        type: branch
        include_match: '^(.*master.*|[a-z]*/borrow_.*)$'

    depends_on:
      borrow_scenarios:
        type: job
        job_key: borrow_scenarios
        states: [passed]

    context:

      task_defaults:
        max_trials: 10
        include:
          - cider-ci_v4/task_components/database.yml
          - cider-ci_v4/task_components/precompile_assets.yml

      include:
        - cider-ci_v4/shared/main_context.yml
        - cider-ci_v4/tasks/borrow_problematic_scenarios.yml
