jobs:

  borrow_scenarios:

    name: 'Borrow: Scenarios'

    description: |
      Run Borrow scenarios under MRI

    priority: -1

    run_when:
      any for now:
        type: branch
        include_match: '^.+$'

    context:

      task_defaults:
        include:
          - cider-ci_v4/task_components/database.yml
          - cider-ci_v4/task_components/precompile_assets.yml

      include:
        - cider-ci_v4/shared/main_context.yml
        - cider-ci_v4/tasks/borrow_scenarios.yml
