jobs:

  manage_problematic_scenarios:

    name: 'Manage: Problematic Scenarios'

    description: |
      Run Manage problematic scenarios under MRI

    priority: -1

    run_when:
      any for now:
        type: branch
        include_match: '^.+$'
      manage scenarios job has passed:
        type: job
        job: manage_scenarios
        states: [passed]

    context:

      task_defaults:
        max_trials: 10
        include:
          - cider-ci_v4/task_components/database.yml
          - cider-ci_v4/task_components/precompile_assets.yml

      include:
        - cider-ci_v4/shared/main_context.yml
        - cider-ci_v4/tasks/manage_problematic_scenarios.yml
