jobs:

  meta:

    name: Meta
    description: |
      Various superordinate quality assurance tasks

    run_when:
      any branch name:
        type: branch
        include_match: '^.*$'

    depends_on:
      borrow_manage_code_checks:
        type: job
        job_key: borrow_manage_code_checks
        states: [passed]
      borrow_scenarios:
        type: job
        job_key: borrow_scenarios
        states: [passed]
      manage_scenarios:
        type: job
        job_key: manage_scenarios
        states: [passed]
      admin_code_checks:
        type: job
        job_key: admin_code_checks
        states: [passed]
      admin_scenarios:
        type: job
        job_key: admin_scenarios
        states: [passed]
      procurement_code_checks:
        type: job
        job_key: procurement_code_checks
        states: [passed]
      procurement_scenarios:
        type: job
        job_key: procurement_scenarios
        states: [passed]

    context:
      task-defaults:
        max_trials: 1
        traits:
          Ruby: true

      tasks:
        git_branch_current:
          name: "git tree contains latest commit from origin/master"
          scripts:
            main:
              body: cider-ci/bin/check_if_branch_current
