jobs:

  borrow-manage-code-checks:

    name: 'Borrow/Manage: Code Checks'

    description: |
      Run static checks and metrics: complexity, duplication, code format

    run-on:
    - type: branch
      include-match: '[a-z]*/(borrow|manage)_.*'
      exclude-match: '^(.*no-ci.*)$'
    - type: branch
      include-match: '^(.*master.*)$'
      exclude-match: '^(.*no-ci.*)$'

    context:

      _cider-ci_include:
        - cider-ci/shared/code-checks-context.yml

      tasks:

        lint_ruby:
          name: Lint/Stylecheck with Rubocop
          scripts:
            test:
              body: bundle exec rubocop
