jobs:

  good-to-merge:

    name: Good To Merge

    descriptions: |
      This job depends on all other tests and checks
      and it will pass if and only if all dependencies have passed.
      Status of this job is **used by github's "branch protection"**!

    depends-on:
    - type: job
      job: borrow-scenarios
      states: [passed]
    - type: job
      job: manage-scenarios
      states: [passed]
    - type: job
      job: admin-scenarios
      states: [passed]
    - type: job
      job: procurement-scenarios
      states: [passed]
    - type: job
      job: borrow-manage-code-checks
      states: [passed]
    - type: job
      job: admin-code-checks
      states: [passed]
    - type: job
      job: procurement-code-checks
      states: [passed]
    - type: job
      job: meta
      states: [passed]

    run-on:
    - type: branch
      include-match: '^.*$'
      exclude-match: '^(.*no-ci.*)$'

    context:
      tasks:
        all:
          scripts:
            body: echo 'Yay, all dependencies have passed!'
