jobs:

  manage-problematic-scenarios:

    name: 'Manage: Problematic Scenarios'

    description: |
      Run problematic features (except engines) under MRI

    priority: -1

    depends-on:
    - type: job
      job: manage-scenarios
      states: [passed]

    run-on:
    - type: branch
      include-match: '[a-z]*/manage_.*$'
      exclude-match: '^(.*no-ci.*)$'
    - type: branch
      include-match: '^(.*master.*)$'
      exclude-match: '^(.*no-ci.*)$'

    context:
      task-defaults:
        max-auto-trials: 10

      _cider-ci_include:
        - cider-ci/shared/tests-context.yml
        - cider-ci/tasks/manage_problematic_scenarios.yml
