jobs:

  meta:

    name: Meta
    description: |
      Various superordinate quality assurance tasks

    depends-on:
    - type: job
      job: borrow-scenarios
      states: [passed]
    - type: job
      job: manage-scenarios
      states: [passed]
    - type: job
      job: admin-scenarios
      states: [passed]
    - type: job
      job: procurement-scenarios
      states: [passed]

    run-on:
    - type: branch
      include-match: '^.*$'
      exclude-match: '^(.*no-ci.*)$'

    context:
      task-defaults:
        max-auto-trials: 1
        traits:
          linux: true
          ruby: true

      tasks:
        # increase-of-problematic-tests:
        #   name: "Number of problematic tests did not increase"
        #   scripts:
        #     main:
        #       body: "cider-ci/bin/check_problematic_scenarios.rb"

        git-branch-current:
          name: "git tree contains latest commit from origin/master"
          scripts:
            main:
              body: "cider-ci/bin/check_if_branch_current"
